name: BookStore CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Bookstore

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore NuGet Packages
        run: dotnet restore BookStore.slnx

      - name: Build Solution
        run: dotnet build BookStore.slnx --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish BookStore.slnx --configuration Release --output ./publish --no-build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BookStore
          path: Bookstore/publish