name: Mirror GitHub to Azure DevOps

on:
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Azure DevOps
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git remote add azure \
            https://:${AZURE_DEVOPS_PAT}@mhpm.visualstudio.com/Bookstore/_git/Bookstore

          git push azure --mirror
